
changes = [{'className': 'kwb',
            'pat': r'\b(?P<value>False|None|True|and|class|def|global|in|is|lambda|nonlocal|not|or)\b'},
           {'className': 'cls',
            'pat': r'\bclass</span> (?P<value>\w+)', 'add': ['class</span> ', '']},
           {'className': 'fn',
            'pat': r'\bdef</span> (?P<value>.+)\(', 'add': ['def</span> ', '(']},
           {'className': 'kwr',
            'pat': r'\b(?P<value>as|assert|break|continue|del|elif|else|except|finally|for|from|if|import|pass|raise|return|try|while|with|yield)\b'},
           {'className': 'fn',
            'pat': r'\b(?P<value>\babs|divmod|input|open|staticmethod|all|enumerate|int|ord|str|any|eval|isinstance|pow|sum|basestring|execfile|issubclass|print|super|bin|file|iter|property|tuple|bool|filter|len|range|type|bytearray|float|list|raw_input|unichr|callable|format|locals|reduce|unicode|chr|frozenset|long|reload|vars|classmethod|getattr|map|repr|xrange|cmp|globals|max|reverse|zip|compile|hasattr|memoryview|round|__import__|complex|hash|min|set|delattr|help|next|setattr|dict|hex|object|slice|dir|id|oct|sorted)\b'},
           {'className': 'num',
            'pat': r'(?P<value>[e\+]?[e\-]?\b\d+)\b'},
           {'className': 'str',
            'pat': r"(?P<value>'.*?')"},
           {'className': 'doc',
            'pat': r'(?P<value>#.*)\n', 'add': ['', '\n']},
           {'className': 'doc',
            'pat': r'(?P<value>""".*""")'},
           {'className': 'doc',
            'pat': r"(?P<value>'''.*''')"}, ]
